Update error messages inline with cli commands
IBM/ibmcloud-volume-file-vpc pull request #11
Opened 2022-01-20 08:03 UTC by prankulmahajan

2022-01-20 08:32 UTC, contsto commented
:thumbsup: Coverage remained same at [92.3265%]

2022-01-20 10:04 UTC, sameshai commented on common/messages/messages_en.go
> +		Action:      "Verify that the volume ID exists. Run 'ibmcloud is shares' to list available volumes in your account. If the ID is correct, try to delete the volume with the 'ibmcloud is volume-delet
can we change the volume delete command to ibmcloud is share-delete

2022-01-20 10:06 UTC, sameshai commented on common/messages/messages_en.go
> +		Action:      "Verify that a volume access point for your volume exists. Run `ibmcloud is share-targets <VOLUME_ID>` to list all mount targets for a file share. Check if volume ID and access point I
If this message is displayed to user can we change this to Run `ibmcloud is share-targets <VOLUME_ID>` to list all volume access point for a volume.

2022-01-20 10:07 UTC, sameshai commented on common/messages/messages_en.go
> +		Action:      "Verify that a volume access point for your volume exists. Run `ibmcloud is share-targets <VOLUME_ID>` to list all mount targets for a file share. Check if volume ID and VPC ID is vali
Same here

2022-01-20 10:14 UTC, sameshai commented on common/messages/messages_en.go
> +		Action:      "User need to review all access points and delete them first before deleting volume. Run `ibmcloud is share-targets <VOLUME_ID>` to get the mount targets for the file share. ",
same here

2022-01-20 12:04 UTC, contsto commented
:thumbsup: Coverage remained same at [92.3265%]

2022-02-03 05:43 UTC, sameshai commented on common/messages/messages_en.go
> +		Action:      "Verify that a volume access point for your volume exists. Run `ibmcloud is share-targets <VOLUME_ID>` to list all volume access point for a file share. Check if volume ID and access p
Run `ibmcloud is share-targets <VOLUME_ID>` to list all volume access point for a volume.

2022-02-03 05:43 UTC, sameshai commented on common/messages/messages_en.go
> +		Action:      "Verify that a volume access point for your volume exists. Run `ibmcloud is share-targets <VOLUME_ID>` to list all volume access point for a file share. Check if volume ID and VPC ID i
Run ibmcloud is share-targets <VOLUME_ID> to list all volume access point for a volume.

2022-02-03 05:43 UTC, sameshai requested changes

2022-02-03 05:43 UTC, sameshai commented on common/messages/messages_en.go
> +		Action:      "User need to review all access points and delete them first before deleting volume. Run `ibmcloud is share-targets <VOLUME_ID>` to get the volume access point for the file share. ",
Run ibmcloud is share-targets <VOLUME_ID> to list all volume access point for a volume.

2022-02-07 10:51 UTC, sameshai commented on common/messages/messages_en.go
> +		Description: "No mount target could be found for the specified file share ID '%s' and mount point ID '%s'",
mount point ID --> moutn target ID

2022-02-07 10:53 UTC, sameshai commented on common/messages/messages_en.go
> +		Action:      "Verify that a mount point for your file share exists. Run `ibmcloud is share-targets <SHARE_ID>` to list all mount targets for a file share. Check if file share ID and mount target ID
mount point  --> mount target

2022-02-07 10:53 UTC, sameshai commented on common/messages/messages_en.go
> +		Description: "The file share ID '%s' could not create mount taregt for VPC ID %s.",
typo for target

2022-02-08 06:49 UTC, sameshai approved these changes
LGTM

2022-02-08 07:04 UTC, contsto commented
:thumbsup: Coverage remained same at [92.5417%]

2022-02-22 11:11 UTC, arahamad approved these changes
lgtm

2022-02-22 11:11 UTC, merged